<?php

namespace Mitch\Bundle\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findByIds($ids)
    {
        $q = $this->createQueryBuilder('p')
                  ->select('p')
                  ->where('p.id IN (:ids)')
                  ->setParameter('ids', $ids)
                  ->getQuery()
                  ->getResult();
        return $q;
    }

}
